[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ollama_api"
version = "0.1.0"
description = "A comprehensive Python client for the Ollama API"
authors = [
    { name = "Lloyd Handyside", email = "ace1928@gmail.com" }
]
license = {text = "MIT"}

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
requires-python = ">=3.8"
dependencies = [
    "requests>=2.25.0",
    "aiohttp>=3.8.0",
    "colorama>=0.4.4",
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0.0",
    "pytest-cov>=2.12.0",
    "black>=23.0.0",
    "isort>=5.10.0",
    "mypy>=0.910",
    "types-requests",
]
docs = [
    "sphinx>=4.0.0",
    "sphinx-rtd-theme>=1.0.0",
]

[project.urls]
"Homepage" = "https://github.com/Ace1928/ollama_api"
"Bug Tracker" = "https://github.com/Ace1928/ollama_api/issues"

[tool.setuptools]
py-modules = [
    "ollama_api", 
    "cli", 
    "client", 
    "exceptions"
]
# Removed the license_files property as it's not valid here
# The LICENSE file is already included via MANIFEST.in

[tool.black]
line-length = 88
target-version = ["py38"]
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
