[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ollama_toolkit"
version = "0.1.7"
description = "A comprehensive Python client library for the Ollama API"
authors = [
    {name = "Lloyd Handyside", email = "ace1928@gmail.com"},
    {name = "Eidos", email = "eidos@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.6"
license = {text = "MIT"}
urls = {repository = "https://github.com/Ace1928/ollama_toolkit"}

[tool.black]
line-length = 88
target-version = ["py38"]
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
